#!/bin/sh
#time=$(($1*0.9))
#echo $time | awk '{print int($0/3600),int($0%3600/60),$0%3600%60}'
for (( i = $1; i > 0; i-- )); do echo -en "Clicks left: $i Percentage done: $((100-($i * 100 / $1)))% \r"; sleep 0.1; xdotool click --repeat 2 1; done
