#!/bin/bash

CLIPBOARD=$(xsel -b -o)
if TITLE=$(youtube-dl -q --no-playlist -e "$CLIPBOARD" 2>&1); then
	TITLE=${TITLE//&/and}
	TITLE=${TITLE//>/}
	TITLE=${TITLE//</}
else
	#notify-send "playVid:" "Unforseen Consecvenses"
	notify-send "playVid: " "$TITLE"
	exit
fi

if youtube-dl --no-playlist -s -q -f bestvideo "$CLIPBOARD" > /dev/null 2>&1 ;  then
	bspc rule -a mpv -o desktop=V
	notify-send "playMedia - MPV:" "$TITLE"
	mpv --autofit-larger=100% --volume=60 $CLIPBOARD 
else
	notify-send "playMedia - MPV:" "$TITLE"
	bspc rule -a URxvt -o desktop=V state=floating center=on
	urxvt -e mpv --no-audio-display "$CLIPBOARD"
fi

